on:
  push:
    branches:
      - main

jobs:
  image-push:
    name: Docker Image Build and Push
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_OIDC_ARN }}
      - uses: aws-actions/amazon-ecr-login@v2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: true
          file: Infra/AWS/SAM/Dockerfile
          tags: ${{ secrets.IMAGE_REGISTRY_URL }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max